name: Unit tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: '0.8.13'
      - run: uv sync --python 3.12 --frozen
      - run: uv run ruff check src scripts tests
      - run: uv run ruff format --check src scripts tests
      - run: uv run pytest -q
